/* Umpire verification code for mgr */

/* !!!!! This file is automatically generated by a wrapper-engine !!!!! */


#include "umpi_internal.h"



int umpi_vcode_MPI_Comm_free_g_pre (umpi_op_t * op)
{
int rc = 0;
assert(op);
rc |= umpi_handle_comm_free (op);
return rc;
} /* umpi_vcode_MPI_Comm_free_g_pre */


/*------------ Wrapper not calling preop processing */


int umpi_vcode_MPI_Scatter_g_pre (umpi_op_t * op)
{
int rc = 0;
assert(op);
/* need to find recvtype_commit_op and reserve it... */
rc |= umpi_mgr_get_comm_recvtypemap (op);
/* need to reserve type_commit_op at root... */
rc |= umpi_mgr_get_root_type_commit_op (op);
return rc;
} /* umpi_vcode_MPI_Scatter_g_pre */


/*------------ Wrapper not calling preop processing */


int umpi_vcode_MPI_Scatterv_g_pre (umpi_op_t * op)
{
int rc = 0;
assert(op);
/* need to find recvtype_commit_op and reserve it... */
rc |= umpi_mgr_get_comm_recvtypemap (op);
/* need to reserve type_commit_op at root... */
rc |= umpi_mgr_get_root_type_commit_op (op);
return rc;
} /* umpi_vcode_MPI_Scatterv_g_pre */


/*------------ Wrapper not calling preop processing */


int umpi_vcode_MPI_Type_commit_g_pre (umpi_op_t * op)
{
int rc = 0;
assert(op);
rc |= umpi_mgr_save_typemap (op);
return rc;
} /* umpi_vcode_MPI_Type_commit_g_pre */


/*------------ Wrapper not calling preop processing */


int umpi_vcode_MPI_Type_free_g_pre (umpi_op_t * op)
{
int rc = 0;
assert(op);
rc |= umpi_mgr_free_typemap (op, 0 /* FALSE */ );
return rc;
} /* umpi_vcode_MPI_Type_free_g_pre */


/*------------ Wrapper not calling preop processing */


/*eof*/
