/* Umpire verification code for mgr header file */

/* !!!!! This file is automatically generated by a wrapper-engine !!!!! */



#ifndef _UMPI_MPI_MGR_VERIFY_H
#define _UMPI_MPI_MGR_VERIFY_H



extern int umpi_vcode_MPI_Comm_free_g_pre (umpi_op_t * op);
extern int umpi_vcode_MPI_Scatter_g_pre (umpi_op_t * op);
extern int umpi_vcode_MPI_Scatterv_g_pre (umpi_op_t * op);
extern int umpi_vcode_MPI_Type_commit_g_pre (umpi_op_t * op);
extern int umpi_vcode_MPI_Type_free_g_pre (umpi_op_t * op);

#endif

/*eof*/
