/* Umpire verification code for outfielder header file */

/* !!!!! This file is automatically generated by a wrapper-engine !!!!! */



#ifndef _UMPI_MPI_OUTFIELDER_VERIFY_H
#define _UMPI_MPI_OUTFIELDER_VERIFY_H




#endif

/*eof*/
