/* Umpire code for copying umpi_ops header file */

/* !!!!! This file is automatically generated by a wrapper-engine !!!!! */



#ifndef _UMPI_MPI_COPY_OP_H
#define _UMPI_MPI_COPY_OP_H



extern void umpi_copy_op_MPI_Allgatherv(umpi_op_t*op, umpi_op_t*newop);
extern void umpi_copy_op_MPI_Alltoallv(umpi_op_t*op, umpi_op_t*newop);
extern void umpi_copy_op_MPI_Cart_coords(umpi_op_t*op, umpi_op_t*newop);
extern void umpi_copy_op_MPI_Cart_create(umpi_op_t*op, umpi_op_t*newop);
extern void umpi_copy_op_MPI_Cart_get(umpi_op_t*op, umpi_op_t*newop);
extern void umpi_copy_op_MPI_Cart_map(umpi_op_t*op, umpi_op_t*newop);
extern void umpi_copy_op_MPI_Cart_rank(umpi_op_t*op, umpi_op_t*newop);
extern void umpi_copy_op_MPI_Cart_sub(umpi_op_t*op, umpi_op_t*newop);
extern void umpi_copy_op_MPI_Dims_create(umpi_op_t*op, umpi_op_t*newop);
extern void umpi_copy_op_MPI_Gatherv(umpi_op_t*op, umpi_op_t*newop);
extern void umpi_copy_op_MPI_Graph_create(umpi_op_t*op, umpi_op_t*newop);
extern void umpi_copy_op_MPI_Graph_get(umpi_op_t*op, umpi_op_t*newop);
extern void umpi_copy_op_MPI_Graph_map(umpi_op_t*op, umpi_op_t*newop);
extern void umpi_copy_op_MPI_Graph_neighbors(umpi_op_t*op, umpi_op_t*newop);
extern void umpi_copy_op_MPI_Group_excl(umpi_op_t*op, umpi_op_t*newop);
extern void umpi_copy_op_MPI_Group_incl(umpi_op_t*op, umpi_op_t*newop);
extern void umpi_copy_op_MPI_Group_range_excl(umpi_op_t*op, umpi_op_t*newop);
extern void umpi_copy_op_MPI_Group_range_incl(umpi_op_t*op, umpi_op_t*newop);
extern void umpi_copy_op_MPI_Group_translate_ranks(umpi_op_t*op, umpi_op_t*newop);
extern void umpi_copy_op_MPI_Reduce_scatter(umpi_op_t*op, umpi_op_t*newop);
extern void umpi_copy_op_MPI_Scatterv(umpi_op_t*op, umpi_op_t*newop);
extern void umpi_copy_op_MPI_Startall(umpi_op_t*op, umpi_op_t*newop);
extern void umpi_copy_op_MPI_Testall(umpi_op_t*op, umpi_op_t*newop);
extern void umpi_copy_op_MPI_Testany(umpi_op_t*op, umpi_op_t*newop);
extern void umpi_copy_op_MPI_Testsome(umpi_op_t*op, umpi_op_t*newop);
extern void umpi_copy_op_MPI_Type_create_indexed_block(umpi_op_t*op, umpi_op_t*newop);
extern void umpi_copy_op_MPI_Type_create_subarray(umpi_op_t*op, umpi_op_t*newop);
extern void umpi_copy_op_MPI_Type_get_contents(umpi_op_t*op, umpi_op_t*newop);
extern void umpi_copy_op_MPI_Type_create_darray(umpi_op_t*op, umpi_op_t*newop);
extern void umpi_copy_op_MPI_Type_indexed(umpi_op_t*op, umpi_op_t*newop);
extern void umpi_copy_op_MPI_Waitall(umpi_op_t*op, umpi_op_t*newop);
extern void umpi_copy_op_MPI_Waitany(umpi_op_t*op, umpi_op_t*newop);
extern void umpi_copy_op_MPI_Waitsome(umpi_op_t*op, umpi_op_t*newop);

#endif

/*eof*/
